/*******************************************************************************
 * Copyright (c) 2014, Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/*!
 * @header      ID3v2-Frame-APIC.h
 * @copyright   (c) 2014 - Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * @abstract    ID3v2 APIC frame
 */

#ifndef ID3V2_V23_FRAME_APIC
#define ID3V2_V23_FRAME_APIC

namespace ID3v2
{
    namespace Frame
    {
        namespace v23
        {
            class APIC: public AbstractFrame
            {
                public:
                        
                        enum class PictureType
                        {
                            Other               = 0x00,
                            FileIcon            = 0x01,
                            OtherFileIcon       = 0x02,
                            CoverFront          = 0x03,
                            CoverBack           = 0x04,
                            LeafletPage         = 0x05,
                            Media               = 0x06,
                            LeadArtist          = 0x07,
                            Artist              = 0x08,
                            Conductor           = 0x09,
                            Band                = 0x0A,
                            Composer            = 0x0B,
                            LyricistWriter      = 0x0C,
                            RecordingLocation   = 0x0D,
                            DuringRecording     = 0x0E,
                            DuringPerformance   = 0x0F,
                            MovieScreenCapture  = 0x10,
                            BrightColouredFish  = 0x11,
                            Illustration        = 0x12,
                            BandLogotype        = 0x13,
                            PublisherLogotype   = 0x14
                        };
                        
                        std::string to_string( PictureType value );
                        
                        APIC( void );
                        virtual ~APIC( void );
                        
                        std::string GetDescription( void ) const;
                        
                        uint8_t                GetTextEncoding( void )       const;
                        std::string            GetMimeType( void )           const;
                        PictureType            GetPictureType( void )        const;
                        std::string            GetPictureTypeString( void )  const;
                        std::string            GetPictureDescription( void ) const;
                        std::vector< uint8_t > GetPictureData( void )        const;
                        
                protected:
                        
                        void ProcessData( void );
                        
                private:
                        
                        class  IMPL;
                        IMPL * impl;
            };
        }
    }
}

#endif /* ID3V2_V23_FRAME_APIC */
