/*******************************************************************************
 * Copyright (c) 2014, Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      ID3v2-Tag.h
 * @copyright   (c) 2014 - Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * @abstract    ID3v2 tag
 */

#ifndef __ID3V2_TAG__
#define __ID3V2_TAG__

namespace ID3v2
{
    class Tag
    {
        public:
            
            typedef enum
            {
                FlagUnsynchronisation       = 0,
                FlagExtendedHeader          = 1,
                FlagExperimentalIndicator   = 2
            }
            Flag;
            
            Tag( std::string path );
            Tag( const Tag & tag );
            
            virtual ~Tag( void );
            
            Tag & operator =( const Tag & tag );
            
            bool                    IsValid( void ) const;
            Version                 GetVersion( void ) const;
            unsigned char           GetFlags( void ) const;
            bool                    HasFlag( Flag flag ) const;
            std::size_t             GetSize( void );
            ExtendedHeader        * GetExtendedHeader( void );
            std::vector< Frame * >  GetFrames( void ) const;
            Frame                 * GetFrameWithName( std::string name ) const;
            
        private:
            
            class  IMPL;
            IMPL * impl;
    };
}

#endif /* __ID3V2_TAG__ */
