/*******************************************************************************
 * Copyright (c) 2014, Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      ID3v2-PrivateTypes.h
 * @copyright   (c) 2014 - Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * @abstract    ID3v2 private types
 */

#ifndef __ID3V2_PRIVATE_TYPES__
#define __ID3V2_PRIVATE_TYPES__

typedef struct
{
    char id[ 3 ];       /* ID3v2/file identifier   "ID3" */
    char version[ 2 ];  /* ID3v2 version           $03 00 */
    char flags;         /* ID3v2 flags             %abc00000 */
    char size[ 4 ];     /* ID3v2 size              4 * %0xxxxxxx */
}
ID3v2Header;

typedef struct
{
    char size[ 4 ];     /* Extended header size   $xx xx xx xx */
    char flags[ 2 ];    /* Extended Flags         $xx xx */
    char padding[ 4 ];  /* Size of padding        $xx xx xx xx */
}
ID3v2ExtendedHeader;

typedef struct
{
    char   id[ 3 ];     /* Frame ID       $xx xx xx xx (four characters) */
    char   size[ 3 ];   /* Size           $xx xx xx xx */
}
ID3v22Frame;

typedef struct
{
    char   id[ 4 ];     /* Frame ID       $xx xx xx xx (four characters) */
    char   size[ 4 ];   /* Size           $xx xx xx xx */
    char   flags[ 2 ];  /* Flags          $xx xx */
}
ID3v23Frame;

#endif /* __ID3V2_PRIVATE_TYPES__ */
